---
- name: Download Jenkins repo apt URL 
  apt_key:
    url: "{{jenkins.repo_URL}}"
    state: present 
  become: yes 

- name: apt update
  apt:
    name: '*'
    state: latest
  
- name: Install java
  apt:
    name: "{{java}}"
    state: present
  become: yes

- name: Install jenkins
  apt:
    name: "{{jenkins}}" 
    state: present

- name: Import jenkins key from url
    ansible.builtin.rpm_key:
     apt_key:
       url: "{{jenkins.repo_URL}}"
       state: present
     become: yes

- name: Start jenkins
  ansible.builtin.systemd:
   name: jenkins
   state: started
  