AWSTemplateFormatVersion: 2010-09-09
Resources:

  myS3Bucket:

    Type: "AWS::S3::Bucket"

    Properties:

      BucketName: "playdatenown2"

 

  playdatenowapp1:

    Type: AWS::ElasticBeanstalk::Application

    Properties:

      ApplicationName: "playdatenowapp1"

  myConfigTemplate:

    Type: AWS::ElasticBeanstalk::ConfigurationTemplate

    Properties:

      ApplicationName:

        Ref: "playdatenowapp1"

      SolutionStackName: "64bit Amazon Linux 2 v4.2.18 running Tomcat 8.5 Corretto 11"




  enviromant:

    Type: AWS::ElasticBeanstalk::Environment

    Properties:

      ApplicationName:

        Ref: "playdatenowapp1"

      EnvironmentName: playdatenow-env1

      SolutionStackName: "64bit Amazon Linux 2 v4.2.18 running Tomcat 8.5 Corretto 11"

      OptionSettings:

          - Namespace: aws:elasticbeanstalk:environment

            OptionName: EnvironmentType

            Value: SingleInstance

          - Namespace: aws:autoscaling:launchconfiguration

            OptionName: IamInstanceProfile

            Value: aws-elasticbeanstalk-ec2-role

          - Namespace: aws:elasticbeanstalk:environment

            OptionName: ServiceRole

            Value: aws-elasticbeanstalk-service-role

          - Namespace: aws:elasticbeanstalk:environment

            OptionName: EnvironmentType
            
            Value: LoadBalanced