AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  MyAliasHostedZoneId:
    Type: String
    Default: Z2NYPWQ7DFZAZH # see beanstalk @ eu-west-1: https://docs.aws.amazon.com/general/latest/gr/rande.html
  MyHostedZoneName:
    Type: String
    Default: ""

Conditions:
  CreateDNSRecordCondition: !Not [!Equals [ !Ref MyHostedZoneName, "" ]]

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: playdatanew4
  BeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref AWS::StackName
      Description: !Ref AWS::StackName

  BeanstalkConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref BeanstalkApplication
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: t2.large
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SSHSourceRestriction
        Value: !Sub "tcp, 22, 22, 127.0.0.1/32"
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: aws-elasticbeanstalk-ec2-role
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '1'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: ServiceRole
        Value: aws-elasticbeanstalk-service-role
      SolutionStackName: 64bit Amazon Linux 2 v4.2.18 running Tomcat 8.5 Corretto 8

  BeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref BeanstalkApplication
      CNAMEPrefix: !Ref AWS::StackName
      EnvironmentName:  !Ref AWS::StackName
      TemplateName: !Ref BeanstalkConfigurationTemplate

  BeanstalkDnsRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateDNSRecordCondition
    Properties:
      HostedZoneName: !Ref MyHostedZoneName
      Name: !Sub ${AWS::StackName}.${MyHostedZoneName}
      Type: A
      AliasTarget:
        HostedZoneId: !Ref MyAliasHostedZoneId
        DNSName: !Sub ${AWS::StackName}.${AWS::Region}.elasticbeanstalk.com