AWSTemplateFormatVersion: 2010-09-09
Resources:

  myS3Bucket:

    Type: "AWS::S3::Bucket"

    Properties:

      BucketName: "playdatenow0"

 

  playdatenow0:

    Type: AWS::ElasticBeanstalk::Application

    Properties:

      ApplicationName: "playdatenow0"

  myConfigTemplate:

    Type: AWS::ElasticBeanstalk::ConfigurationTemplate

    Properties:

      ApplicationName:

        Ref: "playdatenow0"

      SolutionStackName: "64bit Amazon Linux 2 v4.2.18 running Tomcat 8.5 Corretto 11"




  enviromant:

    Type: AWS::ElasticBeanstalk::Environment

    Properties:

      ApplicationName:

        Ref: "playdatenow0"

      EnvironmentName: playdatenow-env

      SolutionStackName: "64bit Amazon Linux 2 v4.2.18 running Tomcat 8.5 Corretto 11"

      OptionSettings:

          - Namespace: aws:elasticbeanstalk:environment

            OptionName: EnvironmentType

            Value: SingleInstance

          - Namespace: aws:autoscaling:launchconfiguration

            OptionName: IamInstanceProfile

            Value: aws-elasticbeanstalk-ec2-role

          - Namespace: aws:elasticbeanstalk:environment

            OptionName: ServiceRole

            Value: aws-elasticbeanstalk-service-role